# Day 1 - Linear Algebra Basics for AI/ML
Today we'll learn about vectors, matrices, dot products, and matrix multiplication using NumPy.

## Concepts
- **Vector**: 1D array of numbers representing magnitude and direction.
- **Matrix**: 2D array of numbers arranged in rows and columns.
- **Dot Product**: Scalar value from multiplying corresponding elements of two vectors and summing them.
- **Matrix Multiplication**: Combining two matrices where the number of columns in the first equals the number of rows in the second.
- These are heavily used in AI for embeddings, transformations, and neural network weight calculations.

In [1]:
import numpy as np
np.set_printoptions(suppress=True)  # For cleaner output

In [2]:
# Creating vectors
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print('Vector 1:', v1)
print('Vector 2:', v2)

# Dot product
dot = np.dot(v1, v2)
print('Dot Product:', dot)

Vector 1: [1 2 3]
Vector 2: [4 5 6]
Dot Product: 32


In [3]:
# Creating matrices
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
print('Matrix 1:\n', m1)
print('Matrix 2:\n', m2)

# Matrix multiplication
mat_mul = np.matmul(m1, m2)
print('Matrix Multiplication:\n', mat_mul)

Matrix 1:
 [[1 2]
 [3 4]]
Matrix 2:
 [[5 6]
 [7 8]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


In [4]:
# Mini Exercise
# Create two 3x3 matrices with random integers 1–10
A = np.random.randint(1, 11, (3, 3))
B = np.random.randint(1, 11, (3, 3))
print('Matrix A:\n', A)
print('Matrix B:\n', B)

# Dot product of first row in both matrices
row_dot = np.dot(A[0], B[0])
print('Dot Product of first rows:', row_dot)

# Matrix multiplication
AB_mul = np.matmul(A, B)
print('Matrix Multiplication (A x B):\n', AB_mul)

Matrix A:
 [[10  2  7]
 [ 2  1  3]
 [ 7  7  7]]
Matrix B:
 [[6 2 4]
 [1 9 3]
 [4 9 8]]
Dot Product of first rows: 92
Matrix Multiplication (A x B):
 [[ 90 101 102]
 [ 25  40  35]
 [ 77 140 105]]
